AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a simple Amazon Linux Instance and allow SSH connectivity.
Resources:
  EC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  EC2Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: EC2Policy
      PolicyDocument:
        Statement:
          - Action:
              - 's3:List*'
              - 's3:Get*'
            Effect: Allow
            Resource: '*'
      Roles:
        - Ref: EC2Role
  EC2Profile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - Ref: EC2Role
  AllowSshFromPublic:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH access from anywhere
      SecurityGroupIngress:
        - FromPort: '22'
          ToPort: '22'
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SSHAccessSG
  SimpleInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: codestar
      InstanceType: t2.micro
      ImageId: ami-b8b45ddf
      SecurityGroupIds:
        - Ref: AllowSshFromPublic
      IamInstanceProfile:
        Ref: EC2Profile
      UserData:
        'Fn::Base64':
          'Fn::Join':
            - |+

            - - '#!/bin/bash'
              - yum -y update
              - yum install -y ruby
              - yum install -y aws-cli
              - cd /home/ec2-user
              - >-
                aws s3 cp s3://aws-codedeploy-us-east-2/latest/install .
                --region us-east-2
              - chmod +x ./install
              - ./install auto
      Tags:
        - Key: Name
          Value: xadetDemo
  Repo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: xadet-demo
      RepositoryDescription: Demo for aws
Outputs:
  CloneUrl:
    Value:
      'Fn::GetAtt':
        - Repo
        - CloneUrlHttp
    Description: Repository to clone
  InstanceDns:
    Value:
      'Fn::GetAtt':
        - SimpleInstance
        - PublicDnsName
    Description: Public DNS Name of our Amazon Linux Instnace.
  InstancePublicIp:
    Value:
      'Fn::GetAtt':
        - SimpleInstance
        - PublicIp
    Description: Public IP Name of our Amazon Linux Instance.
